# Generated by Django 4.2.3 on 2023-07-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_control_delete_coltrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='account',
        ),
        migrations.RemoveField(
            model_name='control',
            name='date',
        ),
        migrations.RemoveField(
            model_name='control',
            name='description',
        ),
        migrations.RemoveField(
            model_name='control',
            name='payment_method',
        ),
    ]
