# Generated by Django 4.2.3 on 2023-07-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_remove_control_account_remove_control_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='account',
            field=models.CharField(choices=[('Inter', 'Inter'), ('Caixa', 'Caixa'), ('Clear', 'Clear')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='category',
            field=models.CharField(choices=[('Comida', 'Comida'), ('Carro', 'Carro'), ('Outros', 'Outros')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='type',
            field=models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa'), ('Investimento', 'Investimento')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
