# Generated by Django 4.2.3 on 2023-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_alter_control_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
