# Generated by Django 4.2.3 on 2023-08-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_alter_control_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Control',
        ),
    ]
