# Generated by Django 4.2.3 on 2023-08-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financas', '0007_delete_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('Inter', 'Inter'), ('Caixa', 'Caixa'), ('Clear', 'Clear')], max_length=10, null=True)),
                ('type', models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa'), ('Investimento', 'Investimento')], max_length=30, null=True)),
                ('date', models.DateField(null=True)),
                ('category', models.CharField(choices=[('Comida', 'Comida'), ('Carro', 'Carro'), ('Outros', 'Outros')], max_length=30, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
